# Generated by Django 4.2.6 on 2023-10-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='blog_category_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blog_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
