# Generated by Django 4.2.6 on 2023-10-29 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_blogcategory_blog_category_pic_blogpost_blog_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='blog_category_pic',
            field=models.ImageField(blank=True, null=True, upload_to='category/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blog_pic',
            field=models.ImageField(blank=True, null=True, upload_to='post/'),
        ),
    ]
